"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# DEVELOP
FRONTEND_URL = "http://localhost:5173" 
BACKEND_URL = "http://127.0.0.1:8000/api"

# PRODUCTION
# FRONTEND_URL = "http://parqueapp.eleueleo.com" 
# BACKEND_URL = "http://parqueapp.eleueleo.com/api"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-wepj7d-(spdlkf=vxh%@3m0kk#4&i5a_anwfyhz0h-69x-2s35'

#--NO TOCAR
#SOLO ACTIVAR EN PRODUCCION[
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ["parqueapp.eleueleo.com", "127.0.0.1", "localhost"]

# SECURE_SSL_REDIRECT = True  # Redirige todas las solicitudes HTTP a HTTPS
# SESSION_COOKIE_SECURE = True  # Asegura que las cookies de sesión solo se envíen por HTTPS
# CSRF_COOKIE_SECURE = True  # Asegura que las cookies CSRF solo se envíen por HTTPS
# SECURE_HSTS_SECONDS = 31536000  # Habilita HTTP Strict Transport Security (HSTS) por un año
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Aplica HSTS a subdominios
# SECURE_HSTS_PRELOAD = True  # Permite que el sitio se incluya en la lista de precarga HSTS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Indica que la solicitud proviene de HTTPS
#]

#Solo en Desarrollo
DEBUG = True
ALLOWED_HOSTS = []
SECURE_SSL_REDIRECT = False  # Redirige todas las solicitudes HTTP
SESSION_COOKIE_SECURE = False  # Asegura que las cookies de sesión solo se envíen por HTTP
CSRF_COOKIE_SECURE = False  # Asegura que las cookies CSRF solo se envíen por HTTP

APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'usuarios',
    'parqueadero',
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_extensions',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

]

CORS_ALLOW_ALL_ORIGINS = True 
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE"]
CORS_ALLOW_HEADERS = ["Authorization", "Content-Type", "headers"]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'usuarios/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',  
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'parqueapp',           #  el nombre de su base de datos
        'USER': 'root',             # usuario de MySQL
        'PASSWORD': '12345678',# contraseña de MySQL
        'HOST': 'localhost',
        'PORT': '3306',
}
}

# PRODUCTION
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'parqueappdb',           #  el nombre de su base de datos
#         'USER': 'parqueapp',             # usuario de MySQL
#         'PASSWORD': '1234.AppDB',# contraseña de MySQL
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djang  oproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'usuarios.validators.CustomPasswordComplexityValidator',  # << Este es el que tú creaste
    },
]

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'es'
USE_I18N = True
USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    
)

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_SECRET'),
            'key': ''
        }
    },
    'facebook': {
        'APP': {
            'client_id': config('FACEBOOK_CLIENT_ID'),
            'secret': config('FACEBOOK_SECRET'),
            'key': ''
        }
    }
}

# Cambios según las nuevas configuraciones de django-allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuración de correo para el envío de emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'parqueappreservas@gmail.com'
EMAIL_HOST_PASSWORD = 'lbcr wpay znje qotm'  # Esta es una app password, así que está bien usarla

AUTH_USER_MODEL = 'usuarios.Usuario'  # Usa el nombre correcto de tu app


TIME_ZONE = 'America/Bogota'  # Zona horaria de Colombia
USE_TZ = True

ASGI_APPLICATION = 'backend.asgi.application'  


# Configuración simple para channel layers usando Redis (recomendado)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


#SECRET_KEY = config('SECRET_KEY')

import cloudinary
import cloudinary.uploader
import cloudinary.models

cloudinary.config(
    cloud_name="dgktoozdm",
    api_key="946841153651718",
    api_secret="EjEugnnqQ5QAGA-4zHU0DjXjPZA"
)
