# Generated by Django 5.2 on 2025-05-14 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id_parqueadero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_disponible', models.IntegerField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parqueadero_set_parqueadero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
