# Generated by Django 5.2 on 2025-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueadero',
            name='capacidad_disponible',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='capacidad_total',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='id_parqueadero',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='id_propietario',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='precio_hora',
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
