# Generated by Django 5.2 on 2025-05-22 03:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Admin', 'Admin'), ('Operario', 'Operario'), ('Root', 'Root')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_restauracion', models.CharField(blank=True, max_length=4, null=True)),
                ('codigo_creado', models.DateTimeField(blank=True, null=True)),
                ('codigo_validado', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_usuario_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id_parqueadero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_disponible', models.IntegerField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_propietario', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('matriz', models.JSONField(default=list)),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parqueadero_set_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EspacioParqueadero',
            fields=[
                ('id_espacio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_espacio', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Fuera de servicio', 'Fuera de servicio')], max_length=20)),
                ('id_parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.parqueadero')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.espacioparqueadero')),
                ('id_parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.parqueadero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo'), ('PayPal', 'PayPal')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id_cancelacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_cancelacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_reseña', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.parqueadero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
