# Generated by Django 5.2 on 2025-05-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Admin', 'Admin'), ('Operario', 'Operario'), ('Root', 'Root')], max_length=20),
        ),
    ]
