# Generated by Django 5.2 on 2025-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueadero',
            name='capacidad_disponible',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='columnas',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='filas',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='id_propietario',
        ),
        migrations.RemoveField(
            model_name='parqueadero',
            name='matriz',
        ),
        migrations.AddField(
            model_name='espacioparqueadero',
            name='columna',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacioparqueadero',
            name='fila',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='precio_hora',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
