# Generated by Django 5.2 on 2025-05-29 23:41

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_parqueadero_capacidad_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenParqueadero',
            fields=[
                ('id_imagen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_del_parqueadero', to='usuarios.parqueadero')),
            ],
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='lista_de_imagenes', to='usuarios.imagenparqueadero'),
        ),
    ]
