# Generated by Django 5.2 on 2025-05-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_imagenparqueadero_parqueadero_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueadero',
            name='capacidad_total',
        ),
    ]
