# Generated by Django 5.2 on 2025-05-30 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_parqueadero_capacidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='propietario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
