# Generated by Django 5.2 on 2025-06-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_parqueadero_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Bicicleta', 'Bicicleta')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
