# Generated by Django 5.2 on 2025-06-02 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_reserva_color_reserva_modelo_reserva_placa_and_more'),
    ]

    operations = [
        

    ]
