# Generated by Django 5.2 on 2025-06-03 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_reserva_color_reserva_modelo_reserva_placa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id_usuario',
        ),
    
        migrations.AlterField(
            model_name='reserva',
            name='id_espacio',
            field=models.ForeignKey(db_column='espacio_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.espacioparqueadero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_parqueadero',
            field=models.ForeignKey(db_column='parqueadero_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.parqueadero'),
        ),
    ]
