# Generated by Django 5.2 on 2025-06-02 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_reserva_id_usuario_reserva_cliente_and_more'),
    ]

    operations = [
        
    ]
