# Generated by Django 5.2 on 2025-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_qr_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
