# Generated by Django 5.2 on 2025-06-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_reserva_codigo_qr_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='precio_hora',
            field=models.IntegerField(),
        ),
    ]
