# Generated by Django 5.2 on 2025-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_parqueadero_precio_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacioparqueadero',
            name='nomenclatura',
            field=models.CharField(choices=[('Numerica', 'Numerica'), ('Alfanumerica', 'Alfanumerica')], default='Numérica', max_length=20),
        ),
        migrations.AlterField(
            model_name='espacioparqueadero',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Deshabilitado', 'Deshabilitado')], max_length=20),
        ),
    ]
