# Generated by Django 5.2 on 2025-06-09 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_espacioparqueadero_nomenclatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacioparqueadero',
            old_name='numero_espacio',
            new_name='espacio',
        ),
        migrations.RemoveField(
            model_name='espacioparqueadero',
            name='id_parqueadero',
        ),
        migrations.RemoveField(
            model_name='espacioparqueadero',
            name='nomenclatura',
        ),
        migrations.AlterField(
            model_name='espacioparqueadero',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Deshabilitado', 'Deshabilitado')], max_length=20),
        ),
        migrations.CreateModel(
            name='MapaParqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('nomenclatura', models.CharField(choices=[('Numerica', 'Numerica'), ('Alfanumerica', 'Alfanumerica')], max_length=20)),
                ('parqueadero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapa', to='usuarios.parqueadero')),
            ],
        ),
        migrations.AddField(
            model_name='espacioparqueadero',
            name='mapa',
            field=models.ForeignKey(default=-8364035406, on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='usuarios.mapaparqueadero'),
            preserve_default=False,
        ),
    ]
