# Generated by Django 5.2 on 2025-06-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_rename_numero_espacio_espacioparqueadero_espacio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='color',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(db_column='vehiculo_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.vehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='recordatorios_activos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Bicicleta', 'Bicicleta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='latitud',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='longitud',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
