# Generated by Django 5.2 on 2025-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_reserva_color_remove_reserva_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_reserva',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
