# Generated by Django 5.2 on 2025-06-17 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='qr_usado_entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='qr_usado_salida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('En Curso', 'En Curso'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
