# Generated by Django 5.2 on 2025-06-17 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_reserva_qr_imagen_reserva_qr_usado_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='codigo_qr_texto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='qr_imagen',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='token_qr',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
