# Generated by Django 5.2 on 2025-06-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_reserva_codigo_qr_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='parqueadero_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='usuarios.parqueadero'),
        ),
    ]
