# Generated by Django 5.2 on 2025-06-18 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_usuario_parqueadero_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='parqueadero_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.parqueadero'),
        ),
    ]
