# Generated by Django 5.2 on 2025-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usuario_parqueadero_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacioparqueadero',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Deshabilitado', 'Deshabilitado')], max_length=20),
        ),
    ]
